# Generated by Django 2.1.1 on 2019-03-08 16:48

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics', models.CharField(blank=True, choices=[('Tmax', 'Maximum Temperature'), ('Tmin', 'Minimum Temperature'), ('Rainfall', 'Rainfall')], default='Tmax', max_length=1000, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('content', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'weather_data',
            },
        ),
    ]
